swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Company API"
  contact:
    email: "daniel.minnaar@gmail.com"
host: "localhost"
tags:
- name: "company"
  description: "Manage companies"

paths:
  /company:
    get:
      tags:
      - "company"
      summary: "Get all companies"
      operationId: "getCompanies"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Company"
    post:
      tags:
      - "company"
      summary: "Add a new company"
      description: ""
      operationId: "addCompany"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Company object that will be created"
        required: true
        schema:
          $ref: "#/definitions/Company"
      responses:
        400:
          description: "Invalid company data"
    patch:
      tags:
      - "company"
      summary: "Update an existing company"
      description: ""
      operationId: "updateCompany"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Company object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Company"
      responses:
        400:
          description: "Invalid ISIN supplied"
        404:
          description: "Company not found"

  /company/getByISIN/{isin}:
    get:
      tags:
      - "company"
      summary: "Get company by ISIN"
      operationId: "getCompanyByISIN"
      produces:
      - "application/json"
      parameters:
      - name: "isin"
        in: "path"
        description: "ISIN to filter by"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Company"
        400:
          description: "Invalid ISIN"
        404:
          description: "Company not found"

definitions:
  Company:
    type: "object"
    required:
    - "name"
    - "exchange"
    - "ticker"
    - "isin"
    properties:
      name:
        type: "string"
        example: "Apple, Inc."
      exchange:
        type: "string"
        example: "NASDAQ"
      ticker:
        type: "string"
        example: "AAPL"
      isin:
        type: "string"
        example: "US0378331005"
      website:
        type: "string"
        example: "https://www.apple.com"

