version: '3.4'

networks:
  company-api-dev:
    driver: bridge 

services:
  company-api:
    image: company-api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=companydb;username=companyuser;password=companyuser"
    networks:
      - company-api-dev
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "companyuser"
      POSTGRES_PASSWORD: "companyuser"
      POSTGRES_DB: "companydb"
    networks:
      - company-api-dev
volumes:
  db_volume: